#define VITALITY		0
#define REGENERATION	1
#define RESISTANCE		2
#define STRENGTH		3
#define HASTE			4
#define VAMPIRE			5
#define JETPACK			6
#define CLOAK			7
#define WEAPON_KNOCK	8
#define ARMOR_UPGRADE	9
#define AMMO_STEAL		10
#define ID				11
#define MAX_AMMO		12
#define GRAPPLE_HOOK	13
#define SUPPLY_STATION	14
//#define FREEZE_SPELL	15
#define CREATE_QUAD		15
#define CREATE_INVIN	16
#define POWER_SHIELD	17
#define CORPSE_EXPLODE	18
#define GHOST			19
#define SALVATION		20
#define FORCE_WALL		21
#define AMMO_REGEN		22
#define POWER_REGEN		23
#define BUILD_LASER		24
#define HA_PICKUP		25
#define BUILD_SENTRY	26
#define BOOST_SPELL		27
#define BLOOD_SUCKER	28
#define PROXY			29
#define MONSTER_SUMMON	30
#define SUPER_SPEED		31
#define ARMOR_REGEN		32
#define BOMB_SPELL		33
#define LIGHTNING		34
#define ANTIGRAV		35
#define HOLY_FREEZE		36
#define WORLD_RESIST	37
#define BULLET_RESIST	38
#define SHELL_RESIST	39
#define ENERGY_RESIST	40
#define PIERCING_RESIST	41
#define SPLASH_RESIST	42
#define CACODEMON		43
#define PLAGUE			44
#define FLESH_EATER		45
#define HELLSPAWN		46
#define BEAM			47
#define BRAIN			48
#define MAGMINE			49
#define CRIPPLE			50
#define MAGICBOLT		51
#define TELEPORT		52
#define NOVA			53
#define EXPLODING_ARMOR	54
#define MIND_ABSORB		55
#define LIFE_DRAIN		56
#define	AMP_DAMAGE		57
#define	CURSE			58
#define	BLESS			59
#define	WEAKEN			60
#define	AMNESIA			61
#define	HEALING			62
#define AMMO_UPGRADE	63
#define YIN				64
#define YANG			65
#define FLYER			66
#define MUTANT			67
#define SPIKE			68
#define MORPH_MASTERY	69
#define NAPALM			70
#define TANK			71
#define MEDIC			72
#define METEOR			73
#define AUTOCANNON		74
#define HAMMER			75
#define BLACKHOLE		76
//4.1
#define FIRE_TOTEM		77
#define WATER_TOTEM		78
#define AIR_TOTEM		79
#define EARTH_TOTEM		80
#define DARK_TOTEM		81
#define NATURE_TOTEM	82
#define FURY			83
#define TOTEM_MASTERY	84
#define	BERSERK			85
#define SHIELD			86
#define CALTROPS		87
#define SPIKE_GRENADE	88
#define DETECTOR		89
#define CONVERSION		90
#define DEFLECT			91
#define SCANNER			92
#define EMP				93
#define DOUBLE_JUMP		94
#define LOWER_RESIST	95
#define FIREBALL		96
#define PLASMA_BOLT		97
#define LIGHTNING_STORM	98
#define MIRV			99
#define SPIKER			100
#define HEALER			101
#define OBSTACLE		102
#define GASSER			103
#define COCOON			104
#define ACID			105
#define SPORE			106
#define SELFDESTRUCT    107
#define FLASH			108
#define DECOY			109 // az 3.2b add decoy back into engineer.

#define MAX_ABILITIES	110
