-- pvm variables
q2.print("Lua: Running pvm variables\n")
SKULL_MOVE_HORIZONTAL_SPEED              = 30
SKULL_MOVE_VERTICAL_SPEED                = 30
SKULL_INITIAL_HEALTH                     = 150
SKULL_ADDON_HEALTH                       = 40
SKULL_INITIAL_DAMAGE                     = 10
SKULL_ADDON_DAMAGE                       = 4
SKULL_SEARCH_TIMEOUT                     = 100
CACODEMON_INITIAL_DAMAGE                 = 100
CACODEMON_ADDON_DAMAGE                   = 20
MAX_PIPES                                = 12
P_TANK_PUNCH_RADIUS                      = 224
SPIKEBALL_INITIAL_HEALTH                 = 200
SPIKEBALL_ADDON_HEALTH                   = 30
SPIKEBALL_INITIAL_DAMAGE                 = 100
SPIKEBALL_ADDON_DAMAGE                   = 50
FIRETOTEM_DAMAGE_MULT                    = 6
SENTRY_ADDON_BULLETDAMAGE                = 2