-- pvp variables
q2print("Lua: Running pvp variables\n")
GRENADES_PICKUP                          = 3
SKULL_MOVE_HORIZONTAL_SPEED              = 22
SKULL_MOVE_VERTICAL_SPEED                = 2
SKULL_INITIAL_HEALTH                     = 130
SKULL_ADDON_HEALTH                       = 30
SKULL_INITIAL_DAMAGE                     = 7
SKULL_ADDON_DAMAGE                       = 3
SKULL_SEARCH_TIMEOUT                     = 75
CACODEMON_INITIAL_DAMAGE                 = 70
CACODEMON_ADDON_DAMAGE                   = 14
MACHINEGUN_INITIAL_DAMAGE                = 9
MACHINEGUN_ADDON_DAMAGE                  = 0.5
MACHINEGUN_ADDON_TRACERDAMAGE            = 3
MAX_PIPES                                = 5
P_TANK_PUNCH_RADIUS                      = 170
SPIKEBALL_INITIAL_HEALTH                 = 80
SPIKEBALL_ADDON_HEALTH                   = 10
SPIKEBALL_INITIAL_DAMAGE                 = 40
SPIKEBALL_ADDON_DAMAGE                   = 10
FIRETOTEM_DAMAGE_MULT                    = 4