<?php
require_once 'config.php';

$_db = new PDO("sqlite:$DB_PATH");

/**
 * @return array
 */
function get_query_params()
{
    if (isset($_GET["qty"]) && is_numeric($_GET["qty"]))
        $qty = $_GET["qty"];
    else
        $qty = 25;

    if (isset($_GET["desc"]) && is_bool($_GET["desc"]))
        $desc = $_GET["desc"];
    else
        $desc = true;
    return array($qty, $desc);
}

function classnum_to_class($classnum)
{
    $classes = [
        "Soldier",
        "Poltergeist",
        "Vampire",
        "Mage",
        "Engineer",
        "Knight",
        "Cleric",
        "Necromancer",
        "Shaman",
        "Alien",
        "Weapon Master"
    ];

    return $classes[$classnum - 1];
}

// this was generated by copying the definitions into a cpp file
// then copying GetAbilityString into that file
// then running the preprocessor on that cpp file.
function abilnum_to_abil($ability_number)
{
    switch ($ability_number) {
        case 0:
            return "Vitality";
        case 1:
            return "Regen";
        case 2:
            return "Resist";
        case 3:
            return "Strength";
        case 4:
            return "Haste";
        case 5:
            return "Vampire";
        case 6:
            return "Jetpack";
        case 7:
            return "Cloak";
        case 8:
            return "Knock Weapon";
        case 9:
            return "Armor Upgrade";
        case 10:
            return "Ammo Stealer";
        case 11:
            return "ID";
        case 12:
            return "Max Ammo";
        case 13:
            return "Grapple Hook";
        case 14:
            return "Supply Station";
        case 15:
            return "Auto-Quad";
        case 16:
            return "Auto-Invin";
        case 17:
            return "Power Shield";
        case 18:
            return "Detonate Body";
        case 19:
            return "Ghost";
        case 20:
            return "Salvation Aura";
        case 21:
            return "Force Wall";
        case 22:
            return "Ammo Regen";
        case 23:
            return "PC Regen";
        case 24:
            return "Lasers";
        case 25:
            return "H/A Pickup";
        case 26:
            return "Sentry Guns";
        case 27:
            return "Boost Spell";
        case 28:
            return "Parasite";
        case 29:
            return "Proxy Grenade";
        case 30:
            return "Monster Summon";
        case 31:
            return "Super Speed";
        case 32:
            return "Armor Regen";
        case 33:
            return "Bomb Spell";
        case 34:
            return "Chain Lightning";
        case 35:
            return "Antigrav";
        case 36:
            return "HolyFreeze Aura";
        case 37:
            return "World Resist";
        case 38:
            return "Bullet Resist";
        case 39:
            return "Shell Resist";
        case 40:
            return "Energy Resist";
        case 41:
            return "Piercing Resist";
        case 42:
            return "Splash Resist";
        case 43:
            return "Cacodemon";
        case 44:
            return "Plague";
        case 45:
            return "Corpse Eater";
        case 46:
            return "Hell Spawn";
        case 48:
            return "Brain";
        case 47:
            return "Beam";
        case 49:
            return "Mag Mine";
        case 50:
            return "Cripple";
        case 51:
            return "Magic Bolt";
        case 52:
            return "Teleport";
        case 53:
            return "Nova";
        case 54:
            return "Exploding Armor";
        case 55:
            return "Mind Absorb";
        case 56:
            return "Life Drain";
        case 57:
            return "Amp Damage";
        case 58:
            return "Curse";
        case 60:
            return "Weaken";
        case 61:
            return "Amnesia";
        case 59:
            return "Bless";
        case 62:
            return "Healing";
        case 63:
            return "Ammo Efficiency";
        case 64:
            return "Yin Spirit";
        case 65:
            return "Yang Spirit";
        case 66:
            return "Flyer";
        case 68:
            return "Spike";
        case 67:
            return "Mutant";
        case 69:
            return "Morph Mastery";
        case 70:
            return "Napalm";
        case 71:
            return "Tank";
        case 72:
            return "Medic";
        case 85:
            return "Berserker";
        case 73:
            return "Meteor";
        case 74:
            return "Auto Cannon";
        case 75:
            return "Blessed Hammer";
        case 76:
            return "Wormhole";
        case 77:
            return "Fire Totem";
        case 78:
            return "Water Totem";
        case 79:
            return "Air Totem";
        case 80:
            return "Earth Totem";
        case 81:
            return "Darkness Totem";
        case 82:
            return "Nature Totem";
        case 83:
            return "Fury";
        case 84:
            return "Totem Mastery";
        case 86:
            return "Shield";
        case 87:
            return "Caltrops";
        case 89:
            return "Defensive boxes";
        case 88:
            return "Spike Grenade";
        case 133:
            return "Detector";
        case 90:
            return "Conversion";
        case 91:
            return "Deflect";
        case 92:
            return "Scanner";
        case 93:
            return "EMP";
        case 94:
            return "Double Jump";
        case 95:
            return "Lower Resist";
        case 96:
            return "Fireball";
        case 97:
            return "Plasma Bolt";
        case 98:
            return "Lightning Storm";
        case 99:
            return "Mirv Grenade";
        case 100:
            return "Spiker";
        case 102:
            return "Obstacle";
        case 101:
            return "Healer";
        case 103:
            return "Gasser";
        case 106:
            return "Spore";
        case 105:
            return "Acid";
        case 104:
            return "Cocoon";
        case 107:
            return "Self Destruct";
        case 108:
            return "Flash";
        case 109:
            return "Decoy";
        default:
            return "<ERROR: NO NAME>";
    }
}